from decouple import config

DEBUG = False

#PORT = 5000

SLACK_TOKEN = config('PROD_BOT_TOKEN')
SLACK_VERIFICATION_TOKEN = config('PROD_AUTH_TOKEN')
SLACK_COMMUNITY_CHANNEL = config('PROD_COMMUNITY_CHANNEL')
SLACK_MENTORS_INTERNAL_CHANNEL = config('PROD_MENTOR_CHANNEL')

AIRTABLE_BASE_KEY = config('PROD_AIRTABLE_BASE_KEY')
AIRTABLE_API_KEY = config('PROD_AIRTABLE_TOKEN')
AIRTABLE_TABLE_NAME = 'Mentor Request'

DB_USERNAME = config('PROD_DB_USERNAME', default='')
DB_PASSWORD = config('PROD_DB_PASSWORD', default='')
DB_DIALECT = config('PROD_DB_DIALECT', default='sqlite')
DB_ADDR = config('PROD_DB_ADDR', default='dev.db')
DB_NAME = config('PROD_DB_NAME', default='')

GOOGLE_RECAPTCHA_SECRET = config('RECAPTCHA_SECRET')

GITHUB_JWT = config('GITHUB_JWT')
GITHUB_REPO_PATH = config('GITHUB_REPO_PATH')

OC_BACKEND_JWT_TOKEN = config('OC_BACKEND_JWT_TOKEN')
OC_BACKEND_URL = config('OC_BACKEND_URL')
