from decouple import config

DEBUG = False

SLACK_TOKEN = config('OPCODE_TOKEN')
SLACK_VERIFICATION_TOKEN = config('OPCODE_VERIFICATION_TOKEN')
SLACK_COMMUNITY_CHANNEL = config('OPCODE_COMMUNITY_ID')
SLACK_MENTORS_INTERNAL_CHANNEL = config('OPCODE_MENTORS_INTERNAL_CHANNEL')

AIRTABLE_BASE_KEY = config('OPCODE_AIRTABLE_BASE_KEY')
AIRTABLE_API_KEY = config('OPCODE_AIRTABLE_TOKEN')
AIRTABLE_TABLE_NAME = 'Mentor Request'

DB_USERNAME = config('PROD_DB_USERNAME')
DB_PASSWORD = config('PROD_DB_PASSWORD')
DB_DIALECT = config('PROD_DB_DIALECT')
DB_ADDR = config('PROD_DB_ADDR')
DB_NAME = config('PROD_DB_NAME')

GOOGLE_RECAPTCHA_SECRET = config('RECAPTCHA_SECRET')

GITHUB_JWT = config('GITHUB_JWT')
GITHUB_REPO_PATH = config('GITHUB_REPO_PATH')

OC_BACKEND_JWT_TOKEN = config('OC_BACKEND_JWT_TOKEN')
OC_BACKEND_URL = config('OC_BACKEND_URL')
